#!/usr/bin/env python3
"""
Tax Blotter — Generate IRS Form 8949-compatible CSV for Kalshi trades.
"""

from __future__ import annotations

import csv
import sqlite3
from datetime import datetime
from pathlib import Path

# Form 8949 columns: Description, Date Acquired, Date Sold, Proceeds, Cost Basis, Gain/Loss, etc.

def format_date(ts: int) -> str:
    return datetime.fromtimestamp(ts).strftime('%Y-%m-%d')

def generate_blotter(db_path: Path, output_path: Path, year: int = None):
    if year is None:
        year = datetime.now().year
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    # Fetch all closed trades with P&L
    cur.execute("""
        SELECT ticker, side, entry_price_cents, exit_price_cents, contracts, entry_ts, exit_ts
        FROM trades
        WHERE exit_ts IS NOT NULL AND exit_status = 'filled'
        AND strftime('%Y', datetime(exit_ts, 'unixepoch')) = ?
    """, (str(year),))
    rows = cur.fetchall()
    conn.close()

    with open(output_path, 'w', newline='') as f:
        writer = csv.writer(f)
        # Header for Form 8949
        writer.writerow([
            'Description', 'Date Acquired', 'Date Sold', 'Proceeds', 'Cost Basis',
            'Gain/Loss', 'Code', 'Adjustment', 'Notes'
        ])
        for ticker, side, entry_cents, exit_cents, contracts, entry_ts, exit_ts in rows:
            # Kalshi: yes/no contracts. For simplicity, treat each contract as 1 unit.
            # Proceeds = exit_price * contracts (in dollars)
            proceeds = exit_cents * contracts / 100.0
            cost = entry_cents * contracts / 100.0
            gain = proceeds - cost
            # Determine if short-term (held < 1 year)
            hold_days = (exit_ts - entry_ts) / 86400
            code = 'S' if hold_days < 365 else 'L'
            description = f"{ticker} {side.upper()} x{contracts}"
            writer.writerow([
                description,
                format_date(entry_ts),
                format_date(exit_ts),
                f"{proceeds:.2f}",
                f"{cost:.2f}",
                f"{gain:.2f}",
                code,
                "",  # Adjustment
                f"Auto-generated by alpha_trader; side={side}"
            ])
    print(f"Generated tax blotter: {output_path} ({len(rows)} rows)")

if __name__ == "__main__":
    repo = Path(__file__).parent.parent
    db = repo / 'data' / 'alpha_trader.db'
    out = repo / 'reports' / f'8949_{datetime.now().year}.csv'
    out.parent.mkdir(exist_ok=True)
    generate_blotter(db, out)
